# Site settings
title: Martin Josefsson, indie programmer
description: > # this means to ignore newlines until "baseurl:"
  Let us talk about hashes. I make blockchain programs, and am an avid user of functional programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.martinjosefsson.com" # the base hostname & protocol for your site
github_username:  fromheten

# Build settings
markdown: kramdown
